[package]
name = "ttg"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.29.1"
egui = "0.29.1"

catppuccin-egui = { version = "5.3.0", default-features = false, features = ["egui29"] }

rustyline = { version = "14.0.0", features = [
    "with-file-history",
    "with-fuzzy",
] }
